export { ReactComponent as ChairIcon } from "./chair.svg";
export { ReactComponent as PersonIcon } from "./person.svg";
export { ReactComponent as PercentIcon } from "./percent.svg";
export { ReactComponent as ComeIn } from "./comeIn.svg";
export { ReactComponent as NotAllow } from "./notAllow.svg";
export { ReactComponent as HistoryIcon } from "./history.svg";
export { ReactComponent as SettingIcon } from "./setting.svg";
export { ReactComponent as DashboardIcon } from "./dashboard.svg";
export { ReactComponent as LogoIcon } from "./logo.svg";
